//@flow
export const LAB4_CHANGE_IS_BUSY_CREATE_MEMORY_OBJECTS = "LAB4_CHANGE_IS_BUSY_CREATE_MEMORY_OBJECTS";
export const LAB4_START_TESTING_MEMORY_LIST = "LAB4_START_TESTING_MEMORY_LIST";
export const LAB4_FINISHED_TESTING_MEMORY_LIST = "LAB4_FINISHED_TESTING_MEMORY_LIST";
