//@flow
export const LAB3_CHANGE_IS_BUSY_CREATE_MEMORY_OBJECTS = "LAB3_CHANGE_IS_BUSY_CREATE_MEMORY_OBJECTS";
export const LAB3_START_TESTING_MEMORY_LIST = "LAB3_START_TESTING_MEMORY_LIST";
export const LAB3_FINISHED_TESTING_MEMORY_LIST = "LAB3_FINISHED_TESTING_MEMORY_LIST";
